apiVersion: v1
kind: Service
metadata:
  name: svc-test
  namespace: test
spec:
  ports:
  - name: web3
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
